on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.40.0"
    steps:
      - run: sudo dnf install -y gcc gtk3-devel graphene-devel glib2-devel git xorg-x11-server-Xvfb
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        name: "Docs"
        with:
          command: doc
      - run: xvfb-run --auto-servernum cargo test
      - uses: actions-rs/cargo@v1
        name: "Build"
        with:
          command: build
      - run: git diff -R --exit-code
      - name: Cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1

  fmt:
    name: rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  checker:
    name: gtk-rs checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gtk-rs/checker
          ref: master
          path: checker
      - working-directory: checker
        run: cargo build --release
      - run: "./checker/target/release/checker ."
      - run: "./checker/check_init_asserts"
